apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: python:3.11-slim
        command: ["python","-c","print('hello, k8s from a Job')"]
